Repository Jak-Sim/client-web, pull requests merged in 2024-12, with the labels that each got.

#4 update: dev 브랜치 업데이트 반영
  src/app/(pages)/challenge/_components/BottomNav.tsx
  src/app/(pages)/challenge/_components/ChallengeCard.tsx
  src/app/(pages)/challenge/_components/ChallengeList.tsx
  src/app/(pages)/challenge/code/_components/CodeForm.tsx
  src/app/(pages)/challenge/create/_components/CreateChallengeForm.tsx
  src/app/(pages)/challenge/create/_hooks/useTempSaveChallenge.ts
  src/app/(pages)/challenge/create/success/page.tsx
  src/app/(pages)/challenge/page.tsx
  src/app/(pages)/sign-up/_components/SignUp.tsx
  src/assets/images/icons/arrow-right.svg
  src/assets/images/icons/code.svg
  src/assets/images/icons/crown-fill.svg
  src/assets/images/icons/fire.svg
  src/assets/images/icons/index.ts
  src/assets/images/icons/lightning-fill.svg
  src/assets/images/icons/plus-2.svg
  src/assets/images/icons/search-shiny.svg
  src/components/input/Slider.tsx
  src/components/layout/PageLayout.tsx
  src/lib/axios/axios.ts
Labels: feature

#5 feat: 피드페이지 퍼블리싱, 모달관련 컴포넌트 추가
  .gitignore
  next.config.mjs
  package-lock.json
  package.json
  src/app/(pages)/_components/ModalProvider.tsx
  src/app/(pages)/_components/SessionProvider.tsx
  src/app/(pages)/chat/[id]/_components/ChatRoomPage.tsx
  src/app/(pages)/chat/[id]/_components/ChatSendFooter.tsx
  src/app/(pages)/chat/[id]/_components/MyChat.tsx
  src/app/(pages)/chat/[id]/_components/OtherChat.tsx
  src/app/(pages)/chat/[id]/page.tsx
  src/app/(pages)/chat/_components/ChatList.tsx
  src/app/(pages)/chat/_components/ChatListPage.tsx
  src/app/(pages)/chat/_components/ChatTab.tsx
  src/app/(pages)/chat/page.tsx
  src/app/(pages)/feed/[userId]/_components/FeedContents.tsx
  src/app/(pages)/feed/[userId]/_components/FeedUserProfile.tsx
  src/app/(pages)/feed/[userId]/page.tsx
  src/app/(pages)/feed/_components/Title.tsx
  src/app/(pages)/feed/page.tsx
  src/app/(pages)/layout.tsx
  src/app/layout.tsx
  src/assets/images/emojis/Complete.png
  src/assets/images/emojis/Compliment.png
  src/assets/images/emojis/Neighbors.png
  src/assets/images/emojis/Recommend.png
  src/assets/images/icons/Dots.svg
  src/assets/images/icons/Filter.svg
  src/assets/images/icons/Left.svg
  src/assets/images/icons/NoTailArrow.svg
  src/assets/images/icons/Search.svg
  src/assets/images/icons/SmallBadge.svg
  src/assets/images/icons/SmallFlag.svg
  src/assets/images/icons/TailArrow.svg
  src/assets/images/icons/index.ts
  src/assets/images/icons/search.svg
  src/assets/images/placeholder/FeedAvatar.png
  src/components/layout/Header.tsx
  src/components/layout/HeaderBackButton.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ModalPortal.tsx
  src/hooks/useModal.ts
  src/lib/axios/axios.ts
  src/models/Create.ts
  src/models/List.ts
  src/models/Message.ts
  src/models/Rooms.ts
  src/models/chat/Chat.ts
  src/models/chat/Image.ts
  src/models/chat/data-contracts.ts
  src/models/chat/http-client.ts
  src/models/data-contracts.ts
  src/models/templates/http-client.eta
  yarn.lock
Labels: feature

#7 feat: 챌린지 리스트 UI 업데이트 & props 정리
  src/app/(pages)/challenge/_components/BottomNav.tsx
  src/app/(pages)/challenge/_components/ChallengeCard.tsx
  src/app/(pages)/challenge/_components/ChallengeList.tsx
  src/app/(pages)/challenge/code/_components/CodeForm.tsx
  src/app/(pages)/challenge/code/page.tsx
  src/app/(pages)/challenge/page.tsx
  src/assets/images/placeholder/face-sad.png
  src/lib/next-auth/auth.ts
Labels: feature

#8 feat: 챌린지 생성 페이지 기능
  jest.config.ts
  jest.setup.ts
  package.json
  src/app/(pages)/_components/ModalProvider.tsx
  src/app/(pages)/challenge/create/_components/CreateChallengeCancel.tsx
  src/app/(pages)/challenge/create/_components/CreateChallengeForm.tsx
  src/app/(pages)/challenge/create/_components/HashTags.test.tsx
  src/app/(pages)/challenge/create/_components/HashTags.tsx
  src/app/(pages)/challenge/create/_components/TempSaveChallengeButton.tsx
  src/app/(pages)/challenge/create/_components/UploadThumbnail.tsx
  src/app/(pages)/challenge/create/_hooks/useTempSaveChallenge.ts
  src/app/(pages)/challenge/create/page.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ModalPortal.tsx
  tsconfig.json
  yarn.lock
Labels: feature

#9 feat: 챌린지 코드 검색 기능
  src/app/(pages)/challenge/_components/BottomNav.tsx
  src/app/(pages)/challenge/code/_components/CodeForm.tsx
  src/app/(pages)/challenge/code/success/page.tsx
  src/app/(pages)/challenge/create/success/page.tsx
  src/app/(pages)/sign-up/_components/SignUp.tsx
  src/app/globals.css
  src/assets/images/icons/Search.svg
  src/assets/images/icons/loading.svg
  src/components/button/Button.tsx
Labels: feature

#10 feat: 챌린지 정보 페이지 추가
  src/app/(pages)/_components/ModalProvider.tsx
  src/app/(pages)/challenge/[challengeId]/_components/ChallengeModal.tsx
  src/app/(pages)/challenge/[challengeId]/page.tsx
  src/app/(pages)/challenge/_components/ChallengeDetail.tsx
  src/app/(pages)/challenge/_components/ChallengeList.tsx
  src/app/(pages)/challenge/_components/MissionList.tsx
  src/app/(pages)/challenge/_components/ParticipantList.tsx
  src/app/(pages)/challenge/_components/RewardList.tsx
  src/app/(pages)/challenge/_mock/dummyMission.json
  src/app/(pages)/challenge/_mock/dummyParticipant.json
  src/app/(pages)/challenge/_mock/dummyReward.json
  src/app/(pages)/challenge/create/_components/HashTags.tsx
  src/app/(pages)/feed/[userId]/page.tsx
  src/app/globals.css
  src/assets/images/icons/calendar-check.svg
  src/assets/images/icons/check.svg
  src/assets/images/icons/chevron-down.svg
  src/assets/images/icons/clock.svg
  src/assets/images/icons/coins.svg
  src/assets/images/icons/gem.svg
  src/assets/images/icons/index.ts
  src/assets/images/placeholder/face-default.png
  src/components/accodion/Accodion.tsx
  src/components/chip/Chip.tsx
  src/types/challenge.ts
Labels: feature

#12 refactor: 해시태그 이벤트 개선
  src/app/(pages)/challenge/create/_components/HashTags.test.tsx
  src/app/(pages)/challenge/create/_components/HashTags.tsx
Labels: refactor

#18 chore: 마이너한 린트, UI, import 오류 수정
  src/app/(pages)/challenge/[challengeId]/page.tsx
  src/app/(pages)/challenge/code/page.tsx
  src/assets/images/icons/index.ts
Labels: bug

#19 refactor: 챌린지 페이지
  src/app/(pages)/_components/ModalProvider.tsx
  src/app/(pages)/challenge/[challengeId]/_components/AddItemButton.tsx
  src/app/(pages)/challenge/[challengeId]/_components/NewChallengeItemModal.tsx
  src/app/(pages)/challenge/[challengeId]/_components/NewMission.tsx
  src/app/(pages)/challenge/[challengeId]/_components/NewReward.tsx
  src/app/(pages)/challenge/[challengeId]/_components/Progress.tsx
  src/app/(pages)/challenge/[challengeId]/_components/UserChallengeCard.tsx
  src/app/(pages)/challenge/[challengeId]/detail/_components/ChallengeModal.tsx
  src/app/(pages)/challenge/[challengeId]/detail/page.tsx
  src/app/(pages)/challenge/[challengeId]/page.tsx
  src/app/(pages)/challenge/_components/MissionItem.tsx
  src/app/(pages)/challenge/_components/MissionList.tsx
  src/app/(pages)/challenge/_components/RewardItem.tsx
  src/app/(pages)/challenge/_components/RewardList.tsx
  src/app/(pages)/challenge/_mock/dummyReward.json
  src/app/(pages)/challenge/code/_components/CodeForm.tsx
  src/app/(pages)/challenge/code/page.tsx
  src/app/globals.css
  src/assets/images/icons/check.svg
  src/assets/images/icons/hamburger.svg
  src/assets/images/icons/heart-fill.svg
  src/assets/images/icons/heart.svg
  src/assets/images/icons/index.ts
  src/assets/images/icons/plus.svg
  src/assets/images/icons/speaker.svg
  src/components/button/Button.tsx
  src/components/layout/Header.tsx
  src/components/tab/LinkTabs.tsx
  tailwind.config.ts
Labels: feature

#20 feat: 공통 에러 페이지 업데이트
  src/app/error.tsx
  src/lib/next-auth/auth.ts
  src/utils/formatErrorMessage.ts
Labels: feature

#21 feat: Challenge api 관련 작업
  db.json
  next.config.mjs
  package.json
  src/app/(pages)/auth/sign-up/_components/SignUp.tsx
  src/app/(pages)/challenge/[challengeId]/_components/ChallengeContents.tsx
  src/app/(pages)/challenge/[challengeId]/_components/NewChallengeItemModal.tsx
  src/app/(pages)/challenge/[challengeId]/_components/UserChallengeCard.tsx
  src/app/(pages)/challenge/[challengeId]/detail/page.tsx
  src/app/(pages)/challenge/[challengeId]/page.tsx
  src/app/(pages)/challenge/_components/ChallengeCard.tsx
  src/app/(pages)/challenge/_components/ChallengeDetail.tsx
  src/app/(pages)/challenge/_components/ChallengeList.tsx
  src/app/(pages)/challenge/code/_components/CodeForm.tsx
  src/app/(pages)/challenge/create/_components/CreateChallengeForm.tsx
  src/app/(pages)/challenge/page.tsx
  src/components/tab/LinkTabs.tsx
  src/models/challenge/Challenge.ts
Labels: feature
